import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../../styles/PageStyles/Learn.module.css";
//import { GlobalContext } from "../context/GlobalContext";
import { PostCard } from "../../components/PostCard/PostCard";
import postData from "../../data/posts.json";
import * as TiIcons from "react-icons/ti";

export default function PostDetail() {
  const router = useRouter();
  const { id } = router.query;
  <div className={styles.container}>
    <Head>
      <title>Learn</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <div className={styles.titleBar}>
      <div className={styles.backBtn}>
        <TiIcons.TiArrowLeft onClick={() => router.back()} />
      </div>
    </div>

    {postData.posts.map((post, i) => {
      return (
        <a key={post.id} href={`/post/${post.id}`}>
          <PostCard post={post} />
        </a>
      );
    })}
    <div className={styles.post}>
      <h1>Post</h1>
    </div>
  </div>;
}
