import Head from "next/head";
import Image from "next/image";
import LineChart from "../Components/Charts/LineChart";
import CoinList from "../Components/CoinList/CoinList";
import Header from "../Components/Header/Header";
import styles from "../styles/PageStyles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='main'>
        <Header />
        <CoinList />
        <LineChart />
      </div>
    </div>
  );
}
