import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/PageStyles/Learn.module.css'

const Learn = () => {
    return (
        <div className={styles.container}>
        <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.main}>
            Forum
        </div>
        <a href="/">Go Back</a>
    </div>
    )
}

export default Learn
