import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/PageStyles/Learn.module.css";
//import { GlobalContext } from "../context/GlobalContext";
import { PostCard } from "../components/PostCard/PostCard";
import postData from "../data/posts.json";
import * as TiIcons from "react-icons/ti";
import { getContent } from '../utilities/db.js';


const Learn = (props) => {
  //let [globalState, dispatch] = useContext(GlobalContext);
  //console.log(globalState);
  let router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.titleBar}>
        <div className={styles.backBtn}>
          <TiIcons.TiArrowLeft onClick={() => router.back()} />
        </div>
      </div>

      {postData.posts.map((post, i) => {
        return <PostCard post={post} key={i} />;
      })}
      <div className={styles.post}><h1>Post</h1></div>
    </div>
  );
};

export default Learn;
