import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../../../styles/PageStyles/Learn.module.css";
//import { GlobalContext } from "../context/GlobalContext";
import { CommentCard } from "../../../components/CommentCard/CommentCard";
import { PostDetail } from "../../../components/PostDetail/PostDetail";
import postData from "../../../data/posts.json";
import * as TiIcons from "react-icons/ti";

export default function PostDetailPage() {
  const router = useRouter();
  //const { id } = router.query;
  const q = router.query;
  console.log("query obj", router);
  /*
  console.log("THE ID", id);
  const currentPost = (function (id) {
    for (var e of postData.posts) {
      if (e.id === id) {
        console.log("HERE", e);
        return e;
      }
    }
  })(parseInt(id));
  */
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.titleBar}>
        <div className={styles.backBtn}>
          <TiIcons.TiArrowLeft onClick={() => router.back()} />
        </div>
      </div>
      <PostDetail post={postData.posts[0]} />

      {postData.comments.map((comment, i) => {
        return (
          <a key={comment.id}>
            <CommentCard comment={comment} />
          </a>
        );
      })}
    </div>
  );
}
